vitest-dev/vscode

- src/pure/runner.ts
This PR fixes a small bug on Windows (with default settings).
Without any settings, the vitestCommand in `TestRunner`  class will be a `.mjs` file, which is not callable on windows.  So I change it to `node vitest.mjs` on windows by default, and on other operation system, the ./vitest.mjs command should work. 
I'm not quite sure, if this will fix the problem mentioned in #15, but it do solve my problem.
> fix: use 'node vitest.mjs' as default vitest command on windows

- src/pure/runner.ts
This change has been tested on both Windows and OSX test are running and reporting their status back correct.
In order to get it working on windows you have to remove the vitest setting `{PATH: "/path/to/node"}` from your settings.json.
Fixes #15 
Added a new issue which  will maybe make it easier to debug the issue next time #20
> Fix not starting vitest process on windows

- package.json
- src/runHandler.ts
Because debugger is running within vscode without using a the powershell shell we need to bypass the drive letter fix while debugging.
This will fix the issue mentiond in #15
> fix debugging on windows

- package.json
- src/pure/runner.ts
- src/pure/utils.ts
- src/runHandler.ts
I have not found that the latest updates have helped, but I did find that the path issues identified by @AlmarAubel are the issue. These changes make a single path sanitization function which has solved the issues for `runTest()` (normal) on my Windows 10 machine.
> File path corrections for Windows

- package.json
- src/config.ts
- src/watch.ts
I like the Watch Mode for Vitest and thought it would be a nice feature if when making changes you got an immediate pop-up on a test failure, so you know the change that broke it. I made the pop-up an optional  boolean setting.
> Feature suggestion. Add failure notification using vscode message. Optional using extension setting.

- src/pure/runner.ts
When running tests on my machine, I got errors saying:
> Test result not found.
> Are there tests with the same name?
> ...
The issue is that [Uri.fsPath](https://code.visualstudio.com/api/references/vscode-api#Uri) returns a lower case drive letter instead of an upper case drive letter.
As a result, we give vitest a bad command and its internal filter will discard the test file.
Hence giving me the above error.
This PR solved the issue for me.
However, there might be a better place to put the call to sanitizeFilePath()
> handle the case where the command starts with a lower case driver letter

- src/pure/ApiProcess.ts
- src/pure/runner.ts
- src/pure/utils.ts
- src/watch.ts
Various changes to migrate to Vite 3.0. Only tested on Windows 11.
- Use --api.port instead of --api.
- Bind to 127.0.0.1 instead of localhost ([breaking change](https://github.com/vitejs/vite/commit/49c0896))
- Fix parsing error by escaping special characters in test names (e.g., `"add 1 + 1"` => `"add 1 \+ 1"`)
- Stop capitalizing the first character of the test file path name. I'm not entirely sure why this was being done originally, but it was creating a mismatch with the way vitest was gathering the test file names. Vitest does a simple case-sensitive `.includes()` check, so `c:\` was not matching the `C:\` in the paths that vitest is producing. [This case-sensitive matching](https://github.com/vitest-dev/vitest/blob/9dbe4e4af7e580ebe33efe243d4137460014f3e4/packages/vitest/src/node/co …
> Vite 3 migration

- CHANGELOG.md
- package.json
- samples/basic/.vscode/settings.json
- samples/basic/package.json
- samples/basic/pnpm-lock.yaml
- src/pure/ApiProcess.ts
Related to issue https://github.com/vitest-dev/vscode/issues/55
- Changed the vite command parameter for the api to `--api.port` instead of `--api` to allow manual setting of the host. 
- Updated vitest version in the basic sample
- Added a setting to the basic sample to set the host manually
- Updated version and changelog
> Changed the vite command parameter for the --api to --api.port instead

- package.json
- src/StatusBarItem.ts
- src/config.ts
Awesome extension @zxch3n!
Added a small tweak to change the background color of StatusBarItem to "errorBackground" when some tests are failing. An optional setting, true by default.
Of course open to feedback :)
> feat: Changing the background color of StatusBarItem 

- src/watch.ts
Happy Holidays 🎄!
Starting Vitest 0.25.x, Vitest started doing sourcemaps differently and stopped sending the parsed `stacks` as part of the api that this plugin uses to communicate with it.
As a result, test failure would be incorrectly mapped in the UI:
https://user-images.githubusercontent.com/4410247/209554471-395e0da8-fc9e-428c-90eb-8e1e71c13b34.mov
I've openned [a PR in Vitest](https://github.com/vitest-dev/vitest/pull/2563) that fixes this and sends stacks again.
However that PR in Vitest isn't enough by itself. Vitests used to include `sourcePos` (the sourcemapped position of the error) in the `ParsedStack`, but as stacks are now always source mapped, @sheremet-va pointed out this didn't make sense anymore and we removed it.
This PR catters for the case where Vitest does sends the …
> fix: map test failure to correct line with latest Vitest

- src/pure/runner.ts
- test/runner.test.ts
Fixes Run Test on Windows not running the proper test, due to the test pattern argument not being escaped (which is required on Windows when calling spawn with shell: true). Also fixes tests with double quotes in their name not being run properly either.
This partially reverts #69, which itself partially reverted #24. Escaping isn't necessary when debugging, since that calls a VS Code API instead of spawn.
> fix: run single test on Windows not working properly

- src/pure/ApiProcess.ts
- src/watch.ts
Was only waiting a second for vitest to start up before giving up looking for results, which is too short for slower computers. This extends it to wait up to 10 seconds, still short of the original default of 20 seconds. This likely fixes some of the issues reported in #98.
Not addressed here is the issue of no feedback if the client fails to connect, that functionality appears to be missing from vitest's client.
> fix: tests still say Running after test run finishes

- src/pure/isVitestEnv.ts
The code that checks `package.json` to see if Vitest is in the repo is currently not working.
Instead of checking whether the `package.json` file exists on disk, and then reading it, it always reads the file and then check if the content is a valid path.
This have the effect that if a folder uses Vite but not Vitest, it would be recognised as a Vitest folder. This is because checking the `package.json` wouldn't happen, and we would default to checking for the presence of `vite.config.(j|t)s` which would exists in this case.
> fix: read package.json to check if a folder is a Vitest env

- package.json
- src/pure/ApiProcess.ts
- src/pure/runner.ts
- src/runHandler.ts
- yarn.lock
Resolves #109.
Also fixes an issue on Windows where the vitest process was never properly terminated, creating a new node.exe process every test run. `process.kill` doesn't work when `shell: true` is sent to spawn, which is the case on Windows.
> fix: unable to cancel in-progress test runs

- src/pure/utils.ts
This PR is a fix for [#88 Vitest not starting up due to failed version check on windows](https://github.com/vitest-dev/vscode/issues/88)
When node is installed via a version manager like `n` or `nvm`, `spawn` fails `"env: node: No such file or directory".
I've added the `process.execPath` argument to the `spawn` command as recommended in https://github.com/electron/electron/issues/3627#issuecomment-793052457.
This issue is not limited to Windows, it affects macOS as well.
> Fix Vitest not starting up due to failed version check on windows #88

- README.md
- package.json
- src/config.ts
- src/runHandler.ts
The launch configuration used for attaching the debugger sets `skipFiles` to `["<node_internals>/**", "**/node_modules/**"]` to make sure you are only debugging your own code. We experienced issues with the debugger being extremely slow to hit the first breakpoint. Experienced the same behaviour if we used this config with Jest. Setting it to an empty array resolved the issue for us.
Sometimes we also want to debug the `node_modules` so I made this configurable via the `debugExclude` setting, defaults to `["<node_internals>/**", "**/node_modules/**"]`.
> feat: make skipFiles of launch config configurable

- src/pure/utils.ts
- test/utils.test.ts
This is a follow-up PR for #118 which have broken some installs:
- https://github.com/vitest-dev/vscode/issues/88#issuecomment-1398074211
It seems to fix:
- https://github.com/vitest-dev/vscode/issues/124
- https://github.com/vitest-dev/vscode/issues/124
- https://github.com/vitest-dev/vscode/issues/90
- https://github.com/vitest-dev/vscode/issues/131
and probably:
- https://github.com/vitest-dev/vscode/issues/13
In some cases, vitest need to be started using `spawn(vitestCommand.cmd, [...vitestCommand.args, '-v'], envs))`, and in other by using `spawn(process.execPath, [vitestCommand.cmd, ...vitestCommand.args, '-v'], envs))`.
There are lot of OS / Node install combinations, and I don't have a clear picture of which to use and when.
The easiest fix that I could find, was to try both …
> fix: Add better version detection

- src/pure/utils.ts
In my environment my projects are stored in a folder that contains space. Because of this when using this extension it is not possible to identify the installed vitest version.
In my case, my projects are located in `D:/my projects/...`, for example. Meanwhile, version checking takes place via `spawn()` and the entire path to `vitest.cmd` (on Windows, for example) is passed as the first argument:
```js
spawn("D:/my projects/example/node_modules/.bin/vitest.cmd"); // ...
```
However, this is not possible in Node, as the first parameter of `spawn()` essentially needs to be the name of the command (in this case, just `vitest.cmd`), and the path to it must be presented as an option ` cwd`.
I made a small modification during the `spawn()` process so that the command is separated from the path, …
> fix: spawn() requires a command name, not a full path

- src/pure/utils.ts
I brought back drive letter capitalization to fix windows issue. However, I'm still struggling to make it work and I'm not sure why. When I debug it as an extension, I get output like this
```
[INFO 11:29:57 AM] Tests run start
[INFO 11:29:57 AM] [Workspace "basic] Run tests from workspace
[INFO 11:29:57 AM] [Execute Vitest] npx vitest --api.host 127.0.0.1 C:/Users/saito/code/vscode/samples/basic/test/add.test.ts -t "addition add"
[INFO 11:29:57 AM] Start api process at port 51789
[INFO 11:29:57 AM] [RUN] npx vitest --api.host 127.0.0.1 C:/Users/saito/code/vscode/samples/basic/test/add.test.ts -t "addition add"
[INFO 11:29:57 AM] [RUN.cwd] c:/Users/saito/code/vscode/samples/basic
[INFO 11:29:57 AM] WS Close
[INFO 11:29:58 AM] RECONNECT
[INFO 11:29:58 AM] WS Close
[INFO 11:29:58 AM] …
```
> fix: Revert back to drive path capitalization on windows

- src/runHandler.ts
By the time the tests have completed the TestItem reference has changed (I tried to track this down to see if there was an upstream issue that could be resolved, but couldn't identify where this was happening) so this PR updates the finished test check to use the test item's ID instead of the reference.
Before this fix the tests were given the green tick but then immediately afterwards the `run.errored()` call failed the test.
Fixes: #159.
- Run this branch in the development window (F5).
- Open a test file and run a single test.
- The test should complete and there should be no error about missing test results.
- Modify the test (e.g. change the expected value) but DON'T save the file.
- Run the test you modified.
- Again, the test should complete and there should be no error about …
> Fix first-run and unsaved test runs

- src/config.ts
- src/discover.ts
This PR fixes two issues related to test file inclusion/exclusion:
1. in `getCombinedConfig()` the deprecated vscode settings or better its default values, when  not found, always overruled the settings in the vite and vitest configs. By this change the entries in both configuration variants get merged.
Fixes Bugs in:  #187 
2. The fix in `discover.ts` just adds an obviously missing variable, which caused an error
> fix: exclude/include config handling and missing workspacePath

- package.json
- src/discover.ts
- src/extension.ts
- src/runHandler.ts
- src/watch.ts
- yarn.lock
Run tests in continuous mode so the peek view can be controlled by the settings.
Fixes: #148.
- Run this extension.
- Open a test file and change a test to fail.
- Run the failing test and the peek view should appear.
- Close the peek view and then click the Vitest item in the status bar to run the tests in watch mode.
- The tests should run but the peek view should not appear.
- Open settings.json and add `"testing.automaticallyOpenPeekViewDuringAutoRun": true`.
- Run this extension again.
- Open the file with the failing test.
- Click the Vitest item in the status bar to run the tests in watch mode.
- The peek view should appear when the test fails.
> Run tests in continuous mode

- .vscode/launch.json
- README.md
- samples/monorepo-vitest-workspace/.vscode/settings.json
- samples/monorepo-vitest-workspace/package.json
- samples/monorepo-vitest-workspace/packages/react copy/components/Link.tsx
- samples/monorepo-vitest-workspace/packages/react copy/package.json
- samples/monorepo-vitest-workspace/packages/react copy/pnpm-lock.yaml
- samples/monorepo-vitest-workspace/packages/react copy/test/__snapshots__/basic.test.tsx.snap
- samples/monorepo-vitest-workspace/packages/react copy/test/basic.test.tsx
- samples/monorepo-vitest-workspace/packages/react copy/tsconfig.json
- samples/monorepo-vitest-workspace/packages/react copy/vitest.config.ts
- samples/monorepo-vitest-workspace/packages/react/components/Link.tsx
- samples/monorepo-vitest-workspace/packages/react/package.json
- samples/monorepo-vitest-workspace/packages/react/pnpm-lock.yaml
- samples/monorepo-vitest-workspace/packages/react/test/__snapshots__/basic.test.tsx.snap
- samples/monorepo-vitest-workspace/packages/react/test/basic.test.tsx
- samples/monorepo-vitest-workspace/packages/react/tsconfig.json
- samples/monorepo-vitest-workspace/packages/react/vitest.config.ts
- samples/monorepo-vitest-workspace/pnpm-lock.yaml
- samples/monorepo-vitest-workspace/pnpm-workspace.yaml
- samples/monorepo-vitest-workspace/vitest.workspace.ts
Adds a project using `defineWorkspace` from vitest workspace.
I think it could be a great addition to add a sample project, and it could help for https://github.com/vitest-dev/vscode/issues/166, https://github.com/vitest-dev/vscode/issues/110 and https://github.com/vitest-dev/vscode/issues/81
> update(vitest): adds vitest workspace example

- package.json
- src/config.ts
- src/discover.ts
- src/pure/ApiProcess.ts
- src/pure/isVitestEnv.ts
- src/pure/runner.ts
- src/pure/utils.ts
- src/pure/watch/client.ts
- src/pure/watch/vitestConfig.ts
- src/pure/watch/ws-client.ts
- src/watch.ts
- tsconfig.json
- yarn.lock
This PR includes an adaption to the latest vitest distribution v1.2.2 (2024-02-16)
> dev: adapt to vitest@1.2

- .vscode/launch.json
- samples/basic/.vscode/settings.json
Breakpoints are not hit because VS Code is looking at the wrong directory for output files. In addition, there was an issue with the `--api.host` being set twice for the basic configuration.
> fix: debugging not hitting breakpoints

- src/extension.ts
This PR makes it so that the Vitest extension automatically discovers tests on startup. This an explicit action today.
> feat: discover on startup

- src/discover.ts
- src/extension.ts
- src/tags.ts
This feature adds an 'open' tag that you can search for in the Test Explorer to only list tests that are currently open in the editor. Very handy when working on a feature that spans multiple tests.
> feat: add 'open' tag to test files that are open in editor

- package.json
- src/config.ts
- src/extension.ts
This PR adds a new setting that allows for Vite to start watching on startup.
> feat: auto watch on startup setting

- samples/basic/.vscode/settings.json
- samples/basic/test/using.test.ts
- samples/basic/vite.config.ts
- src/pure/parsers/helper.ts
- test/parse.test.ts
- tsconfig.json
- yarn.lock
Today, if a test has the `using` keyword in it (a new TypeScript feature), Vitest won't run or discover that particular test. This fixes that problem.
> feat: support using keyword

- README.md
- package.json
- samples/basic/.vscode/settings.json
- src/config.ts
- src/discover.ts
- src/vscodeUtils.ts
- yarn.lock
This fixes #233. I saw that the methods were actually also marked as obsolete.
This is a breaking change, so a major version bump is probably a good idea.
> fix!: remove default include and exclude

- package.json
The VSCode extension now uses the name `vitest.explorer`.
> feat: update publisher and name

- package.json
- src/StatusBarItem.ts
- src/command.ts
- src/extension.ts
- src/runHandler.ts
After the introduction of #178, there has been a quite critical bug. If you started continuous mode and then at a later point stopped it again, you could never manually run tests again until you restarted VS Code.
This was because watchers weren't disposed properly when continuous mode was being stopped.
This PR fixes that.
It also removes the watch commands, since they are now redundant. VS Code has inbuilt "start continuous mode" commands etc.
> fix!: disabling continuous mode prevents future tests from being run

- README.md
1. Added a link to Visual Studio Marketplace
2. Removed unnecessary screenshots
3. Minor content improvements
> docs: clean up readme file

- src/config.ts
- src/pure/utils.ts
I am using yarn 4 pnp in my project, which is causing the default vitest binary resolution strategy (i.e. digging through `node_modules`) to fail. Given that we can pass in a command with which to run tests, I believe we should be able to use that command to determine the version of vitest. 
Look at the commit history for a summary of each change. I debugged this change by referencing [this PR](https://github.com/cameronbrill/portfolio/pull/20) in the `.vscode/launch.json` debug configuration. After these changes, I can finally run vitest tests in the native VS Code ui!
I appreciate any reviews!
> fix: reference VS Code settings when determining vitest version

- package.json
- pnpm-lock.yaml
- test/tsconfig.json
- tsconfig.base.json
- tsconfig.json
On my IDE, mocha typing wasn't working, so I tweaked tsconfig files for this.
<details><summary>before</summary>
</details>
<details><summary>after</summary>
</details>
> chore: typecheck test files

- test/tsconfig.json
Linter didn't pick up since https://github.com/vitest-dev/vscode/pull/273 is merged before https://github.com/vitest-dev/vscode/pull/279
- https://github.com/vitest-dev/vscode/pull/273
- https://github.com/vitest-dev/vscode/pull/279
> chore: lint tsconfig

- src/api.ts
- src/api/rpc.ts
- src/debug/startSession.ts
- src/runner/runner.ts
- src/runner/testRunData.ts
- src/testTree.ts
- src/testTreeData.ts
- src/worker/actions.ts
- test/TestData.test.ts
> fix: correctly track continuous requests

- samples/monorepo-vitest-workspace/pnpm-lock.yaml
- samples/monorepo-vitest-workspace/vitest.config.ts
- src/worker/actions.ts
- src/worker/rpc.ts
- src/worker/worker.ts
- closes https://github.com/vitest-dev/vscode/issues/319
Extension side is requesting `rpc.getFiles(".../vitest.workspace.ts")`, but worker side had `vitestById = { ".../vitest.config.ts": Vitest }` due to `getId` picking up root config instead of workspace config. 
This was leading to a following `undefined` error since `vitestById[".../vitest.workspace.ts"] === undefined`:
```
2024-03-25 13:38:19.276 [error] TypeError: Cannot read properties of undefined (reading 'server')
at getId (/home/hiroshi/code/others/vitest-vscode/dist/worker.js:925:20)
at globTestFiles (/home/hiroshi/code/others/vitest-vscode/dist/worker.js:949:27)
at Proxy.getFiles (/home/hiroshi/code/others/vitest-vscode/dist/worker.js:995:27)
```
I manually tested on `samples/monorepo-vitest-workspace`.
> fix: fix workspace with root `vite.config.ts`

- scripts/ecosystem-ci.mts
- Fixes https://github.com/vitest-dev/vitest-ecosystem-ci/actions/runs/8415400656/job/23040515890#step:8:418
I was only testing against `--release`, so I didn't consider `@vitest/...`.
Selected run confirmed on my fork:
https://github.com/hi-ogawa/vitest-ecosystem-ci/commit/25542e65a7aa2f74c72ffdb34f213aaa8d1f6351
https://github.com/hi-ogawa/vitest-ecosystem-ci/actions/runs/8416521748/job/23043329462
> test: fix ecosystem-ci

- src/testTree.ts
- src/testTreeData.ts
- test/TestData.test.ts
Related #341
I added a possible fix by registering an inlined item, but we now also throw an error if data is not found.
> fix: throw an error if test data is not found

- samples/basic/test/env.test.ts
- src/api.ts
Followup to https://github.com/vitest-dev/vscode/pull/309
When running the extension on a fresh install I could see the `NODE_ENV` by default is coming through as `true`. If we want to match the behavior of `startVitest` in  https://github.com/vitest-dev/vitest/blob/5c7e9ca05491aeda225ce4616f06eefcd068c0b4/packages/vitest/src/node/cli/cli-api.ts#L40 we should default to `test`.
> Default `NODE_ENV` to `test`

- package.json
The first alias in a language contribution is used as a human readable label. This is used in the status bar as well as the language selector.
> feat: add name for the vitest-snapshot language

- package.json
- pnpm-lock.yaml
- src/api/rpc.ts
- src/debug/debugManager.ts
- src/extension.ts
- src/polyfills.ts
- src/runner/runner.ts
- src/testTree.ts
- src/worker/reporter.ts
- src/worker/setupFile.ts
- src/worker/watcher.ts
> fix: print unhandled errors to tets results tab

- README.md
- package.json
- src/api.ts
- src/config.ts
- src/debug/api.ts
- src/extension.ts
- src/process.ts
Should fix - #393 (will close after conformation)
> fix: run tests with correct CWD

- README.md
- src/api.ts
- src/constants.ts
- src/testTree.ts
- src/utils.ts
> fix: throw an error if Node.js is too low

- src/runner/runner.ts
- test-e2e/basic.test.ts
> fix: don't mark suites state since they are calculated based on children

- src/worker/coverage.ts
Fixes #477
It seems that when using workspace configs the coverage `enabled` flag does not get set to `true`, so the call to `initCoverageProvider` doesn't actually initialize the provider. This causes the report to not generate and coverage to not show.
There is also a similar issue within `waitForReport` where using the coverage config from the context directly doesn't reflect the correct `enabled` flag, so using the local one ensures the flag is set correctly.
I suppose the _correct_ fix here would be figuring out why this flag is not syncing correctly with workspaces, but this is a simple workaround.
This can be validated using the `monorepo-vitest-workspace` sample, after these changes the coverage UI in VSCode should show correctly as in screenshot:
> fix: handle config de-sync when using workspaces

- package.json
- pnpm-lock.yaml
- src/api/child_process.ts
- src/api/resolve.ts
In a Yarn PnP monorepo, when a child repository is vscode workspace root, the pnp.cjs executable is not resolved correctly.
This PR addresses the issue by searching up from the workspace directory to locate the .pnp.cjs file.
`fork` cwd has been adjusted too as the location of the .pnp.cjs file may differ from the working directory. This mismatch caused an infinite loop.
> fix: better pnp.cjs resolution in workspace

- src/api.ts
- src/api/child_process.ts
- src/api/ws.ts
This is effectively the same as what we do already but it can catch unexpected exits better.
> fix: close the rpc when the affected process is closed

- README.md
- package.json
- samples/basic/.vscode/settings.json
- samples/basic/vitest.config.ts
- src/api/child_process.ts
- src/api/ws.ts
- src/config.ts
- src/extension.ts
- src/testTree.ts
- src/worker/collect.ts
- src/worker/types.ts
- src/worker/vitest.ts
- src/worker/watcher.ts
- src/worker/worker.ts
Introduce `vitest.experimentalStaticAstCollect` option for more stable test discovery
> feat: introduce `vitest.experimentalStaticAstCollect` option 

- src/api.ts
- src/api/rpc.ts
- src/runner/runner.ts
- src/worker/vitest.ts
- test-e2e/tester.ts
> fix: run test in the correct project if Vitest workspace is used

- src/worker/collect.ts
Related #515
It is not possible to resolve the dynamic name during collection because it's done statically. but the name _will_ be resolved the next time the test has run.
This fixes the display, but running the test with a button won't work for these tests because we use `testNamePattern` to run tests.
We need to try and find a way to keep the original dynamic names when the collection is triggered. Maybe just ignore static names if the dynamic is known?
> fix: resolve the test message name statically when dynamic expression is used

- samples/basic/src/add.ts
- samples/basic/test/throw.test.ts
- src/runner/runner.ts
- For thrown error scenarios provides the location of the error thrown inside the tested code with fully navigable trace.
- For non throw error scenarios provides additional context on the failed assertion.
|| Before | After |
|--------|--------|--------|
| Assert | ![assertion - before](https://github.com/user-attachments/assets/fb4e70c0-f744-4f1b-a2ee-95c4a1ecfa57) | ![assertion - after](https://github.com/user-attachments/assets/998367a0-9be3-467f-af2d-d70a1c971778) |
| Exception | ![exception - before](https://github.com/user-attachments/assets/1f393147-b4b5-4733-927d-f5cef151025a) | ![exception - after](https://github.com/user-attachments/assets/79e874bc-ac1e-4f38-8e21-9d66b8798cab) |
> Add stack traces to test message for test error.

- src/runner/runner.ts
test:
pnpm typecheck
pnpm lint
pnpm test
+run manually
p.s. sorry, no idea how local vscode typing just worked
> hotfix for adding stack traces for error as the feature was added only in vscode 1.93

- src/worker/coverage.ts
- src/worker/vitest.ts
- src/worker/watcher.ts
> fix: support vitest beta

- src/utils.ts
close: https://github.com/vitest-dev/vscode/issues/542
More background: https://github.com/microsoft/playwright/issues/33996#issuecomment-2542290911
NVM lazy loading use cases such as the Oh My Zsh `nvm` plugin might make node a function which will be executed to set the node path when it is run, so executed the `node` command if it is a function to make it point to the real Node binary.
> fix: node path detection for lazy loading
