package.json
samples/basic/test/.gitignore
samples/basic/test/snapshot.test.ts
src/TestData.ts
src/discover.ts
src/extension.ts
src/pure/runner.ts
src/runHandler.ts

feat: update snapshot from contextmenu

---

src/pure/runner.ts

Removes quotes from run-configuration on windows

fix: run partial test suite on windows (#64)

---

src/StatusBarItem.ts

This PR resolves the #152 issue

fix "NaN%, 2 skipped" bug

---

.github/workflows/build.yml

This PR introduces basic GitHub Actions checks.

ci: add github actions

---

src/discover.ts

The title and PR should speak for itself. This helped me discover the issue that is being solved by PR #232.

fix: improve logging when a parse error occurs

---

yarn.lock

Fixes broken build. Sorry about that. I did try to run all commands locally when I introduced GitHub Actions, but then forgot to commit the lockfile as well.

fix: updated lockfile

---

samples/basic/.vscode/settings.json
samples/basic/test/env.test.ts
src/api.ts

- closes https://github.com/vitest-dev/vscode/issues/305

fix: set env vars `TEST`, `VITEST`, and `NODE_ENV`

---

.github/ISSUE_TEMPLATE/bug_report.yml

This PR introduces a validation step in the issue reporting template to ensure that issues are reported against the latest version of the extension. The rationale behind this change is to streamline the issue resolution process by focusing efforts on current problems, reducing the time spent on issues already addressed in recent updates, and encouraging users to keep their installations updated.

Enhance issue reporting template with version validation

---

src/testTree.ts
src/testTreeData.ts
src/worker/reporter.ts
test/TestData.test.ts

Test name pattern broke due to https://github.com/vitest-dev/vscode/commit/7ce92f16db7f0e33e5ec2596bd20e4075a86cc4a

fix: correctly resolve testNamePattern

---

package.json
pnpm-lock.yaml
src/api.ts
src/utils.ts

fix: use local Node executable

---

.vscode/launch.json
README.md
samples/no-config/package.json
samples/no-config/pnpm-lock.yaml
samples/no-config/src/add.ts
samples/no-config/test/add.test.ts
src/api.ts
src/api/pkg.ts
src/api/resolve.ts
src/config.ts
src/extension.ts
src/runner/runner.ts
src/worker/types.ts
src/worker/vitest.ts
src/worker/worker.ts

feat: support workspaces without a vitest config

---

package.json
src/api.ts
src/api/rpc.ts
src/extension.ts
src/runner/runner.ts
src/testTree.ts
src/worker/vitest.ts

fix: support update snapshots command

---

src/utils.ts

This only works if the installation folder is "Volta".
I don't know how to check for volta otherwise.
I only have a windows machine, I don't know volta's behaviour on linux so I can't check what will happen there.
Fix #382

bugfix(utils): add volta support on win32

---

src/api/pkg.ts

fix: show warnings only for Vitest configs (skip Vite configs)

---

README.md
package.json
samples/basic/vitest.config.d.ts
src/config.ts

fix: exclude d.ts config files by default

---

package.json
patches/@vitest__runner@2.0.5.patch
pnpm-lock.yaml
src/api/pkg.ts
src/api/resolve.ts
src/api/rpc.ts
src/worker/collect.ts

feat: support yarn pnp

---

.vscodeignore
src/api.ts
src/api/resolve.ts
src/debug/api.ts
src/testTree.ts
src/worker/debug.ts
src/worker/init.ts
src/worker/types.ts
src/worker/worker.ts

fix: fully support yarn pnp

---

CONTRIBUTION.md

Updates command in the contribution docs and adds a note about selecting from the multiple samples.

docs: update contribution

---

src/api.ts
src/extension.ts
src/testTree.ts
test-e2e/basic.test.ts
test-e2e/tester.ts

fix: display project name in the icon gutter

---

.github/workflows/ci.yml
src/worker/collect.ts
src/worker/vitest.ts
test-e2e/assertions.ts
test-e2e/basic.test.ts

fix: don't panic when file contains invalid syntax in browser mode

---

.gitignore
.vscode/launch.json
samples/multiple-configs/app1/test-app1.test.ts
samples/multiple-configs/app1/vitest.config.js
samples/multiple-configs/app2/test-app2.test.ts
samples/multiple-configs/app2/vitest.config.js
samples/multiple-configs/package.json
samples/multiple-configs/pnpm-lock.yaml
src/api.ts
src/api/terminal.ts
src/watcher.ts
test-e2e/basic.test.ts
test-e2e/helper.ts

fix: update watched files correctly if there are multiple config files

---

samples/browser/package.json
samples/browser/pnpm-lock.yaml
samples/browser/vitest.config.ts
src/worker/reporter.ts
src/worker/vitest.ts

fix: don't panic when running tests in browser mode with the latest Vitest

---

src/runner/runner.ts
src/testTree.ts

fix: report coverage with negative columns

---

src/api/child_process.ts

fix execargv order

---

src/api/child_process.ts
src/api/terminal.ts
src/api/ws.ts
src/debug.ts
src/worker/init.ts
src/worker/types.ts

fix(terminal): wait for the shell integration to be ready
